# Run an AFL through real AmiBroker and say whether the library actually LOADS.
#
#   .\run-test.ps1                      # self-test: does autotrader-http.afl load?
#   .\run-test.ps1 -Formula <path.afl>  # run your own formula instead
#
# Set SD_AMIBROKER_HOME if AmiBroker is not in C:\Program Files\AmiBroker.
#
# WHY THIS EXISTS
# ---------------
# check-afl.py catches the three AFL parse-time rules we know about, and it is
# fast and needs no AmiBroker. It is still only a model of AmiBroker, and a
# mistake it does not model stops the ENTIRE library from loading - every
# function, for every user, on the first run. This runs the real thing.
#
# Use both: check-afl.py tells you WHERE (file and line), this tells you WHETHER.
#
# VERDICT RULE - read this before changing it
# -------------------------------------------
# PASS requires the marker file AND zero AFL Error dialogs. Not one or the other.
#
# The marker is written by the last line of the test formula, so at first glance
# "marker present" looks like proof the library loaded. It is not. Once the
# dialog watcher started DISMISSING errors, AmiBroker carried on past the broken
# code and still reached that last line - and both known-bad refs reported PASS.
# The marker only ever meant "execution reached the end". Any AFL Error at all
# means the library did not load, whatever the marker says.

param(
    [string]$Formula,
    [int]$TimeoutSec = 180
)

$here    = $PSScriptRoot
$outDir  = Join-Path $here 'out'
$install = if ($env:SD_AMIBROKER_HOME) { $env:SD_AMIBROKER_HOME } else { 'C:\Program Files\AmiBroker' }

if (-not (Test-Path (Join-Path $install 'Broker.exe'))) {
    Write-Host "No Broker.exe under [$install]. Set SD_AMIBROKER_HOME to your AmiBroker folder."
    exit 2
}
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$marker   = Join-Path $outDir 'marker.txt'
$dlgLog   = Join-Path $outDir 'dialogs.log'
$firstErr = Join-Path $outDir 'first-error.txt'
Remove-Item $marker, $dlgLog, $firstErr -ErrorAction SilentlyContinue

# --- the formula ----------------------------------------------------------
# The self-test is generated rather than shipped as a fixed file, because the
# marker path has to be absolute and AFL cannot read an environment variable.
if (-not $Formula) {
    $Formula = Join-Path $outDir 'selftest-library.afl'
    $markerForAfl = $marker -replace '\\', '/'
    @"
/*
 * Generated by run-test.ps1 - do not edit, your changes will be overwritten.
 *
 * The include IS the test. autotrader-http.afl only defines functions and
 * constants and makes no network call, so if AmiBroker can parse the whole
 * include chain, execution reaches the marker below. If any file in the chain
 * fails to parse, AmiBroker aborts and the marker is never written.
 */

#include <autotrader-http.afl>

marker = "$markerForAfl";

fh = fopen( marker, "w" );
if( fh )
{
    fputs( "LIBRARY-LOADED-AND-RAN\n", fh );
    fclose( fh );
}

Filter = 1;
AddColumn( Close, "Close" );
"@ | Set-Content -Path $Formula -Encoding ASCII
    Write-Host "self-test formula: $Formula"
}

# --- make sure AmiBroker is up, with the install dir as CWD ----------------
$proc = Get-Process Broker -ErrorAction SilentlyContinue
if (-not $proc) {
    Write-Host 'AmiBroker not running - starting it'
    $p = Start-Process -FilePath (Join-Path $install 'Broker.exe') -WorkingDirectory $install -PassThru
    $deadline = (Get-Date).AddSeconds(60)
    do {
        Start-Sleep -Seconds 2
        $q = Get-Process -Id $p.Id -ErrorAction SilentlyContinue
        $title = if ($q) { $q.MainWindowTitle } else { $null }
    } while ((Get-Date) -lt $deadline -and [string]::IsNullOrEmpty($title))
}

# A trial build shows a nag dialog at every startup, and while ANY modal is up
# every OLE call blocks. Clear it before touching COM.
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $here 'ab-dialogs.ps1') -Once -LogFile $dlgLog | Out-Null
Start-Sleep -Milliseconds 600

# --- watcher runs CONCURRENTLY with the formula ---------------------------
# It has to: an AFL Error modal blocks Explore(), so a watcher that only ran
# afterwards would wait for something that never finishes.
$watcher = Start-Process -FilePath 'powershell.exe' `
    -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $here 'ab-dialogs.ps1'),
                    '-Seconds',[string]($TimeoutSec + 10),'-LogFile',$dlgLog) `
    -WindowStyle Hidden -PassThru

Write-Host "--- running: $Formula ---"
$sw = [System.Diagnostics.Stopwatch]::StartNew()
$runner = Start-Process -FilePath 'cscript.exe' `
    -ArgumentList @('//nologo', (Join-Path $here 'run-formula.vbs'), $Formula) `
    -NoNewWindow -PassThru `
    -RedirectStandardOutput (Join-Path $outDir 'run.out') `
    -RedirectStandardError  (Join-Path $outDir 'run.err')

if (-not $runner.WaitForExit($TimeoutSec * 1000)) {
    Write-Host "runner timed out after ${TimeoutSec}s - killing"
    $runner | Stop-Process -Force
}
$sw.Stop()

Start-Sleep -Seconds 2
if (-not $watcher.HasExited) { $watcher | Stop-Process -Force }

# --- verdict ---------------------------------------------------------------
Get-Content (Join-Path $outDir 'run.out') -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "  $_" }

$errCount = 0
if (Test-Path $dlgLog) {
    $errCount = @(Select-String -Path $dlgLog -Pattern 'caption=\[AFL Error\]').Count
}
$markerOk = Test-Path $marker

Write-Host "--- AFL errors: $errCount   marker: $markerOk   elapsed: $([int]$sw.Elapsed.TotalSeconds)s ---"

if ($markerOk -and $errCount -eq 0) {
    Write-Host 'PASS - the library loaded and ran in real AmiBroker with no errors.'
    exit 0
}

if (-not $markerOk) {
    Write-Host 'FAIL - no marker: the formula did not run to completion.'
} else {
    Write-Host "FAIL - reached the end but AmiBroker raised $errCount AFL error(s); the library did NOT load cleanly."
}
if (Test-Path $firstErr) {
    Write-Host 'FIRST AFL ERROR (the real defect - the ones after it are fallout):'
    (Get-Content $firstErr) -join ' ' -split '(?=Error \d+\.)' | ForEach-Object {
        if ($_.Trim()) { Write-Host ('    ' + $_.Trim()) }
    }
}
exit 1
